INSERT INTO taobao.category (id_cg, name_cg) VALUES (1, '平板电视');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (2, '马桶');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (3, '沙发');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (4, '电热水器');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (5, '平衡车');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (6, '扫地机器人');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (7, '冰箱');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (8, '空调');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (9, '女表');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (10, '男表');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (11, '男士手拿包');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (12, '男士西服');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (13, '时尚男鞋');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (14, '品牌女装');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (15, '太阳镜');
INSERT INTO taobao.category (id_cg, name_cg) VALUES (16, '安全座椅');
INSERT INTO taobao.login (id_l, username_l, password_l, phone_l, email_l) VALUES (1, 'zms', '123456', '15679109201', '13970501291@qq.com');
INSERT INTO taobao.login (id_l, username_l, password_l, phone_l, email_l) VALUES (2, '淘淘', 'zms13970501291', '13970501291', null);
INSERT INTO taobao.login (id_l, username_l, password_l, phone_l, email_l) VALUES (3, '淘淘', 'zms1944801730', null, '1944801730@qq.com');
INSERT INTO taobao.product (id_pro, name_pro, subTitle_pro, orignalPrice_pro, promotePrice_pro, stock_pro, cid_pro, createDate) VALUES (1, 'Changhong/长虹 65S1安卓智能12核65英寸网络平板LED液晶电视机70 ', '屏大影院 高配12核 安卓智能 ', 4499.01, 3824.16, 84, 1, '2019-08-22 00:00:00');
INSERT INTO taobao.product (id_pro, name_pro, subTitle_pro, orignalPrice_pro, promotePrice_pro, stock_pro, cid_pro, createDate) VALUES (2, '夏普屏PANDA/熊猫 LE39D71S 39英寸智能WiFi液晶平板电视40 42 43 ', '屏大影院 高配12核 安卓智能 ', 2499, 1874.25, 75, 1, '2019-08-22 00:00:00');
INSERT INTO taobao.product (id_pro, name_pro, subTitle_pro, orignalPrice_pro, promotePrice_pro, stock_pro, cid_pro, createDate) VALUES (3, 'Hisense/海信 LED40EC520UA 40英寸4K智能平板液晶电视机WIFI网络 ', '周末 特惠 2189 元还送 精美礼品  ', 2399, 1439.4, 82, 1, '2019-08-23 00:00:00');
INSERT INTO taobao.product (id_pro, name_pro, subTitle_pro, orignalPrice_pro, promotePrice_pro, stock_pro, cid_pro, createDate) VALUES (4, 'Hisense/海信 LED49EC320A 49吋led液晶电视机智能网络平板电视50  ', '新品特惠 十核智能 内置WiFi 咨询有惊喜   ', 2799, 1679.4, 90, 1, '2019-08-23 00:00:00');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (1, 1, 'img/productSingle/665.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (2, 1, 'img/productSingle/663.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (3, 1, 'img/productSingle/664.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (4, 1, 'img/productSingle/661.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (5, 4, 'img/productSingle/676.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (6, 1, 'img/productSingle/675.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (7, 2, 'img/productSingle/674.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (8, 2, 'img/productSingle/673.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (9, 2, 'img/productSingle/672.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (10, 2, 'img/productSingle/672.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (11, 2, 'img/productSingle/672.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (12, 3, 'img/productSingle/654.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (13, 3, 'img/productSingle/652.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (14, 3, 'img/productSingle/652.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (15, 3, 'img/productSingle/651.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (16, 3, 'img/productSingle/650.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (17, 4, 'img/productSingle/643.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (18, 4, 'img/productSingle/642.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (19, 4, 'img/productSingle/640.jpg');
INSERT INTO taobao.productimage (id_proimg, pid_proimg, type_proimg) VALUES (20, 4, 'img/productSingle/639.jpg');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (1, '什么垃圾电视，差评！ ', 1, 1, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (2, '哎呦，不错呦~  ', 2, 1, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (3, '哎呦，不错呦~  ', 2, 2, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (4, '哎呦，不错呦~  ', 1, 2, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (5, '电视很好,桌子上有点空空的 ', 1, 3, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (6, '电视很好,桌子上有点空空的 ', 1, 4, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (7, '电视很好,桌子上有点空空的 ', 2, 4, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (8, '电视很好,桌子上有点空空的 ', 3, 4, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (10, '电视很好,桌子上有点空空的 ', 3, 3, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (11, '电视很好,桌子上有点空空的 ', 2, 3, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (12, '电视很好,桌子上有点空空的 ', 2, 2, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (13, '电视很好,桌子上有点空空的 ', 1, 2, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (15, '电视很好,桌子上有点空空的 ', 3, 2, '2019-08-22 00:00:00');
INSERT INTO taobao.review (id_re, content_re, uid_re, pid_re, createDate_re) VALUES (16, '电视很好,桌子上有点空空的 ', 3, 1, '2019-08-22 00:00:00');